action = loadkeyboard,loadtriads,reporteffort,quit
corpus = scripts/test_corpus.txt
keyboard_input = keyboards/qwerty.conf
mode = english
triads_overlap = yes
triads_min_freq = 1
<effort_model>
<<include effort/01.conf>>
</effort_model>
